### ISSUE TITLE
Change the value of hbase.regionserver.thrift.framed for security?

### ISSUE THREAD

**Issue by odunybrad** [Boostport/hbase-phoenix-all-in-one#2]
Thanks for providing this useful container. 

I have a question about one hbase config:  It seems you keep the default setting of `hbase.regionserver.thrift.framed for security` to false. 

However, The [official document](https://hbase.apache.org/book.html#hbase.regionserver.thrift.framed) recommends to set `hbase.regionserver.thrift.framed` to at least `true`, for security:  "This is the recommended transport for thrift servers and requires a similar setting on the client side. Changing this to false will select the default transport, vulnerable to DoS when malformed requests are issued due to THRIFT-601."

It is also recommended in Cloudera's [troubleshoorting page](https://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_hbase_troubleshooting.html) to set hbase.regionserver.thrift.framed and hbase.regionserver.thrift.compact to true.

Shall we change the two settings to `true`? 
Thanks.

**Comment by F21** [comment]
`hbase.regionserver.thrift.frame` and `hbase.regionserver.thrift.compact` are already set to true when the server is started: https://github.com/Boostport/hbase-phoenix-all-in-one/blob/master/start-hbase-phoenix.sh#L28

Can you check `/opt/hbase/conf/hbase-site.xml` in the container after starting the server to see if they are set correctly?
